// Generated by `contrail lexicons generate`. Re-run the command to update; do not edit.
import { defineLexiconConfig } from "@atcute/lex-cli";

export default defineLexiconConfig({
  generate: {
    files: [
      "lexicons/custom/**/*.json",
      "lexicons/pinned/**/*.json",
      "lexicons/pulled/**/*.json",
      "lexicons/generated/**/*.json",
    ],
    outdir: "src/lexicon-types/",
  },
  pull: {
    outdir: "lexicons/pulled/",
    clean: true,
    sources: [
      {
        type: "atproto",
        mode: "nsids",
        nsids: [
          "app.bsky.actor.profile",
          "app.bsky.graph.follow",
          "com.atproto.label.defs",
          "com.atproto.repo.strongRef",
          "community.lexicon.calendar.event",
          "community.lexicon.calendar.rsvp",
          "community.lexicon.location.address",
          "community.lexicon.location.fsq",
          "community.lexicon.location.geo",
          "community.lexicon.location.hthree"
        ],
      },
    ],
  },
});
